apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-demo.fullname" . }}-api
  labels:
{{ include "fullstack-demo.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "fullstack-demo.fullname" . }}-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
