apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullstack-demo.fullname" . }}-secret
  labels:
{{ include "fullstack-demo.labels" . | indent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  RESET_TOKEN: {{ .Values.api.resetToken | quote }}
