apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-dev
resources:
  - namespace.yaml
  - ../../base
replicas:
  - name: python-api
    count: 1
images:
  - name: python-api
    newName: python-api
    newTag: local
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: python-api-config
    behavior: merge
    literals:
      - APP_NAME=Python API Kustomize Dev
      - APP_ENV=dev
      - PORT=8000
