apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  template:
    spec:
      containers:
        - name: python-api
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
