apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo-manual
  hostPath:
    path: /tmp/k8s-storage-demo
