apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-demo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-manual
  volumeName: storage-demo-pv
  resources:
    requests:
      storage: 1Gi
