environment: base

replicaCount: 1

image:
  repository: python-api
  tag: local
  pullPolicy: IfNotPresent

config:
  appName: Python API
  appEnv: kubernetes
  port: "8000"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  host: python-api.local
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
