apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: python-api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: python-api:local
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              value: Curso Kubernetes
            - name: APP_ENV
              value: cluster-local
            - name: PORT
              value: "8000"
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
