apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-api-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "python-api-demo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "python-api-demo.fullname" . }}
    spec:
      containers:
        - name: {{ include "python-api-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_NAME
              value: {{ .Values.app.name | quote }}
            - name: APP_ENV
              value: {{ .Values.app.environment | quote }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
