# Ejemplo ilustrativo.
# Regeneralo con el certificado real del controlador usando kubeseal.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitops-db-credentials
  namespace: sealed-secrets-demo
spec:
  encryptedData:
    username: AgReemplazaConLaSalidaRealDeKubeseal
    password: AgReemplazaConLaSalidaRealDeKubeseal
  template:
    metadata:
      name: gitops-db-credentials
      namespace: sealed-secrets-demo
    type: Opaque
