apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-api.fullname" . }}-config
  labels:
{{ include "python-api.labels" . | indent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENV: {{ .Values.config.appEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
