apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api
  labels:
    release: observability
spec:
  selector:
    matchLabels:
      app: python-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
