apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporte-cada-cinco-min
  namespace: batch-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: reporte
              image: busybox:1.36
              command:
                - sh
                - -c
                - echo Ejecutando tarea programada; date
